events {}

http {
  upstream frontend_app { server frontend:5173; }
  upstream login_service { server login-service:5001; }
  upstream user_service_cluster {
    server user-service-1:5002 max_fails=3 fail_timeout=10s;
    server user-service-2:5002 max_fails=3 fail_timeout=10s;
  }
  upstream matchmaking_service { server matchmaking-service:5003; }
  upstream signaling_service { server signaling-service:5004; }
  upstream ranking_service { server ranking-service:5005; }
  upstream saga_service { server saga-service:5006; }

  server {
    listen 80;

    location /api/auth {
      proxy_pass http://login_service/auth;
      proxy_set_header Host $host;
    }

    location /api/users {
      proxy_pass http://user_service_cluster/users;
      proxy_set_header Host $host;
    }

    location /api/matchmaking {
      proxy_pass http://matchmaking_service/matchmaking;
      proxy_set_header Host $host;
    }

    location /api/questions {
      proxy_pass http://user_service_cluster/questions;
      proxy_set_header Host $host;
    }

    location /api/rooms {
      proxy_pass http://user_service_cluster/rooms;
      proxy_set_header Host $host;
    }

    location /api/ranking {
      proxy_pass http://ranking_service/ranking;
      proxy_set_header Host $host;
    }

    location /api/saga {
      proxy_pass http://saga_service/saga;
      proxy_set_header Host $host;
    }

    location /ws/signaling {
      proxy_pass http://signaling_service/ws/signaling;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
      proxy_set_header Host $host;
    }

    location / {
      proxy_pass http://frontend_app;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
      proxy_set_header Host $host;
    }
  }
}
